## Main

### Import libraries

In [247]:
import pandas as pd
import numpy as np

# model selection
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score

# preprocessing
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder

# model
from sklearn.linear_model import LogisticRegression

# evaluation
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

# pipeline + imbalance handling
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import GridSearchCV

### Parameters

In [248]:
DATA_PATH = "datasets/diabetic_data_imbalanced_0.965.csv"
TARGET_COLUMN = "diabetesmed"
RANDOM_STATE = 18

### Read data

In [249]:
df = pd.read_csv(DATA_PATH)
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,93499158,57292749,Caucasian,Male,[70-80),?,1,1,7,10,...,No,Steady,No,No,No,No,No,No,Yes,<30
1,149276196,27892332,AfricanAmerican,Female,[50-60),?,1,1,7,2,...,No,No,No,No,No,No,No,Ch,Yes,>30
2,154763322,65553282,Caucasian,Female,[90-100),?,1,3,7,3,...,No,No,No,No,No,No,No,No,Yes,NO
3,299038478,108728496,Caucasian,Male,[80-90),?,2,3,7,4,...,No,Steady,No,No,No,No,No,No,Yes,NO
4,267440622,57714192,Caucasian,Female,[70-80),?,2,1,1,14,...,No,Steady,No,No,No,No,No,Ch,Yes,<30

In [250]:
df.shape

(81205, 50)

In [251]:
df.groupby("diabetesMed")["patient_nbr"].count()

diabetesMed
No      2842
Yes    78363
Name: patient_nbr, dtype: int64

In [252]:
df.groupby("diabetesMed")["patient_nbr"].count() * 100 / df.shape[0]

diabetesMed
No      3.499784
Yes    96.500216
Name: patient_nbr, dtype: float64

### Data Preprocessing

In [253]:
clean_df = df.copy()

In [254]:
clean_df.columns = (
    clean_df.columns.str.lower().str.replace(" ", "_").str.replace("-", "_")
)
clean_df.columns

Index(['encounter_id', 'patient_nbr', 'race', 'gender', 'age', 'weight',
       'admission_type_id', 'discharge_disposition_id', 'admission_source_id',
       'time_in_hospital', 'payer_code', 'medical_specialty',
       'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1',
       'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'a1cresult',
       'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'examide', 'citoglipton', 'insulin',
       'glyburide_metformin', 'glipizide_metformin',
       'glimepiride_pioglitazone', 'metformin_rosiglitazone',
       'metformin_pioglitazone', 'change', 'diabetesmed', 'readmitted'],
      dtype='str')

In [255]:
clean_df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide_metformin,glipizide_metformin,glimepiride_pioglitazone,metformin_rosiglitazone,metformin_pioglitazone,change,diabetesmed,readmitted
0,93499158,57292749,Caucasian,Male,[70-80),?,1,1,7,10,...,No,Steady,No,No,No,No,No,No,Yes,<30
1,149276196,27892332,AfricanAmerican,Female,[50-60),?,1,1,7,2,...,No,No,No,No,No,No,No,Ch,Yes,>30
2,154763322,65553282,Caucasian,Female,[90-100),?,1,3,7,3,...,No,No,No,No,No,No,No,No,Yes,NO
3,299038478,108728496,Caucasian,Male,[80-90),?,2,3,7,4,...,No,Steady,No,No,No,No,No,No,Yes,NO
4,267440622,57714192,Caucasian,Female,[70-80),?,2,1,1,14,...,No,Steady,No,No,No,No,No,Ch,Yes,<30

### Data Exploration

In [256]:
for column in clean_df.columns:
    print()
    print("==" * 20)
    print("FEATURE NAME:", column)
    print()
    print("Uniqe values:")
    print(clean_df[column].unique())
    print()
    print("Value counts:")
    print(clean_df[column].value_counts())

========================================
FEATURE NAME: encounter_id

Uniqe values:
[ 93499158 149276196 154763322 ... 417962378   7977348  75109110]

Value counts:
encounter_id
93499158     1
149276196    1
154763322    1
299038478    1
267440622    1
            ..
37946328     1
211832892    1
417962378    1
7977348      1
75109110     1
Name: count, Length: 81205, dtype: int64

========================================
FEATURE NAME: patient_nbr

Uniqe values:
[57292749 27892332 65553282 ... 27646461  4519683 35387685]

Value counts:
patient_nbr
88785891    39
43140906    27
1660293     23
23643405    22
92709351    21
            ..
96095241     1
81811314     1
27646461     1
4519683      1
35387685     1
Name: count, Length: 58276, dtype: int64

========================================
FEATURE NAME: race

Uniqe values:
<ArrowStringArray>
['Caucasian', 'AfricanAmerican', 'Hispanic', '?', 'Asian', 'Other']
Length: 6, dtype: str

Value counts:
race
Caucasian          60597
AfricanAmerican    15344
?                   1913
Hispanic            1612
Other               1245
Asian                494
Name: count, dtype: int64

========================================
FEATURE NAME: gender

Uniqe values:
<ArrowStringArray>
['Male', 'Female', 'Unknown/Invalid']
Length: 3, dtype: str

Value counts:
gender
Female             43327
Male               37876
Unknown/Invalid        2
Name: count, dtype: int64

========================================
FEATURE NAME: age

Uniqe values:
<ArrowStringArray>
[ '[70-80)',  '[50-60)', '[90-100)',  '[80-90)',   '[0-10)',  '[60-70)',
  '[40-50)',  '[20-30)',  '[30-40)',  '[10-20)']
Length: 10, dtype: str

Value counts:
age
[70-80)     20908
[60-70)     18219
[50-60)     13831
[80-90)     13435
[40-50)      7682
[30-40)      2976
[90-100)     2055
[20-30)      1358
[10-20)       605
[0-10)        136
Name: count, dtype: int64

========================================
FEATURE NAME: weight

Uniqe values:
<ArrowStringArray>
[        '?',   '[50-75)', '[100-125)',  '[75-100)',    '[0-25)',   '[25-50)',
 '[125-150)', '[175-200)',      '>200', '[150-175)']
Length: 10, dtype: str

Value counts:
weight
?            78890
[75-100)       976
[50-75)        628
[100-125)      452
[125-150)      114
[25-50)         67
[0-25)          40
[150-175)       25
[175-200)       10
>200             3
Name: count, dtype: int64

========================================
FEATURE NAME: admission_type_id

Uniqe values:
[1 2 3 6 5 4 8 7]

Value counts:
admission_type_id
1    42853
3    15118
2    14970
5     3996
6     3965
8      279
7       16
4        8
Name: count, dtype: int64

========================================
FEATURE NAME: discharge_disposition_id

Uniqe values:
[ 1  3  6 22 18 11 23 13  2  4  5  7 15 27 14 25 24 28  8  9 20 10 16 17
 19]

Value counts:
discharge_disposition_id
1     48191
3     11386
6     10612
18     2461
22     1684
2      1614
11     1154
5       922
25      787
4       622
7       469
23      362
13      307
14      281
28      119
8        85
15       57
24       36
9        19
17       12
16       11
10        5
19        4
27        3
20        2
Name: count, dtype: int64

========================================
FEATURE NAME: admission_source_id

Uniqe values:
[ 7  1  4 17  6  2  3  5 20  8  9 11 22 25 14 10 13]

Value counts:
admission_source_id
7     45900
1     23589
17     5419
4      2544
6      1851
2       879
5       587
20      144
3       138
9       113
8        15
22       12
10        8
11        2
25        2
14        1
13        1
Name: count, dtype: int64

========================================
FEATURE NAME: time_in_hospital

Uniqe values:
[10  2  3  4 14  7  1  6 11  5 12  8  9 13]

Value counts:
time_in_hospital
3     14267
2     13524
4     11290
1     10344
5      8149
6      6124
7      4801
8      3627
9      2515
10     1918
11     1543
12     1216
13     1015
14      872
Name: count, dtype: int64

========================================
FEATURE NAME: payer_code

Uniqe values:
<ArrowStringArray>
[ '?', 'CP', 'MC', 'SP', 'MD', 'CM', 'HM', 'DM', 'OG', 'PO', 'BC', 'UN', 'OT',
 'WC', 'SI', 'CH', 'MP', 'FR']
Length: 18, dtype: str

Value counts:
payer_code
?     30742
MC    26718
HM     4695
SP     4292
BC     3728
MD     3047
UN     2036
CP     2022
CM     1642
OG      898
PO      494
DM      468
CH      118
WC      116
OT       79
MP       67
SI       42
FR        1
Name: count, dtype: int64

========================================
FEATURE NAME: medical_specialty

Uniqe values:
<ArrowStringArray>
[                    'InternalMedicine',
                                    '?',
                     'Emergency/Trauma',
                     'Gastroenterology',
                          'Pulmonology',
                           'Cardiology',
                           'Pediatrics',
                              'Urology',
              'ObstetricsandGynecology',
                      'Surgery-General',
               'Family/GeneralPractice',
                       'Otolaryngology',
                  'Hematology/Oncology',
           'Orthopedics-Reconstructive',
                          'Orthopedics',
                     'Surgery-Thoracic',
                           'Nephrology',
                          'Radiologist',
                     'Surgery-Vascular',
                           'Hematology',
                          'Hospitalist',
                            'Osteopath',
             'Pediatrics-Endocrinology',
                             'Oncology',
                           'Psychiatry',
                           'Gynecology',
                            'Neurology',
                        'Surgery-Neuro',
      'Surgery-Cardiovascular/Thoracic',
               'Pediatrics-Pulmonology',
    'PhysicalMedicineandRehabilitation',
               'Surgery-Cardiovascular',
             'Anesthesiology-Pediatric',
                        'Endocrinology',
                             'Podiatry',
                      'Surgery-Plastic',
                        'Ophthalmology',
                           'Psychology',
                   'InfectiousDiseases',
                              'DCPTEAM',
                            'Radiology',
              'Pediatrics-CriticalCare',
                    'SurgicalSpecialty',
                         'Perinatology',
                    'PhysicianNotFound',
                            'Pathology',
                              'Surgeon',
                 'Pediatrics-Neurology',
          'Psychiatry-Child/Adolescent',
                     'OutreachServices',
                       'Anesthesiology',
                           'Obstetrics',
                         'Rheumatology',
                 'Surgery-Colon&Rectal',
      'Pediatrics-AllergyandImmunology',
 'Obsterics&Gynecology-GynecologicOnco',
         'Pediatrics-EmergencyMedicine',
                 'AllergyandImmunology',
                            'Dentistry',
             'Endocrinology-Metabolism',
       'Pediatrics-Hematology-Oncology',
                'Surgery-Maxillofacial',
                          'Dermatology',
                             'Resident',
                               'Speech',
                 'Cardiology-Pediatric',
                    'Surgery-Pediatric',
     'Surgery-PlasticwithinHeadandNeck',
                 'Psychiatry-Addictive',
        'Pediatrics-InfectiousDiseases',
                      'Neurophysiology',
                       'SportsMedicine',
                           'Proctology']
Length: 73, dtype: str

Value counts:
medical_specialty
?                                39411
InternalMedicine                 11815
Emergency/Trauma                  6420
Family/GeneralPractice            6028
Cardiology                        4167
                                 ...
Psychiatry-Addictive                 1
Pediatrics-InfectiousDiseases        1
Neurophysiology                      1
SportsMedicine                       1
Proctology                           1
Name: count, Length: 73, dtype: int64

========================================
FEATURE NAME: num_lab_procedures

Uniqe values:
[ 77   1  53  37  44  15  27  38  58  40   9  80  34  49  52  48  28  20
  26  19  68  51   3  14  91  25  67  47  21  56  32  39  29   4  42  62
  54  72  57  35  65  17  43  66  33  64  41  63  45  55  50  96  18  36
  23  30  24   5  69  73   2  31  60  61  59  76   8  13  70  16  22  71
  46  82 107  11   7  10  86  78  94  87  12 100  84  81  75  83  74  90
   6  93  85  88  79  95 102  89  92 109  97 101 113 118  98 104  99 108
 120 121 105 103 106 132 111 114 129]

Value counts:
num_lab_procedures
1      2626
43     2240
44     1955
45     1906
46     1733
       ...
120       1
121       1
132       1
114       1
129       1
Name: count, Length: 117, dtype: int64

========================================
FEATURE NAME: num_procedures

Uniqe values:
[3 0 1 2 4 5 6]

Value counts:
num_procedures
0    37701
1    16334
2     9927
3     7411
6     4035
4     3336
5     2461
Name: count, dtype: int64

========================================
FEATURE NAME: num_medications

Uniqe values:
[21 17  8 12 31  7 14 16  5  4 10 13 20 18  9 19 24 27 26 15 11 23 48 25
 32 22 35  6 50  2 36 28 29 33  3 34 40  1 38 30 58 39 42 55 37 44 51 45
 66 60 41 43 46 69 49 65 52 67 61 56 53 47 81 54 59 64 63 68 57 62 75 72
 79 74 70]

Value counts:
num_medications
13    4854
15    4775
12    4734
14    4608
16    4538
      ...
75       2
70       2
81       1
79       1
74       1
Name: count, Length: 75, dtype: int64

========================================
FEATURE NAME: number_outpatient

Uniqe values:
[ 0  3  4  2  1  5  8  6  7  9 11 15 21 24 14 12 17 10 13 27 16 36 29 19
 35 40 20 22 33 28 37 23 38 42 18 26 25 39 34]

Value counts:
number_outpatient
0     67575
1      6914
2      2950
3      1684
4       896
5       436
6       244
7       121
8        77
9        69
10       49
11       38
13       26
14       25
12       25
15       15
16        9
17        7
21        5
20        5
22        4
27        3
19        3
18        3
24        2
36        2
29        2
35        2
33        2
23        2
25        2
40        1
28        1
37        1
38        1
42        1
26        1
39        1
34        1
Name: count, dtype: int64

========================================
FEATURE NAME: number_emergency

Uniqe values:
[ 0  4  1  3  5  2 16  6  8 11 10 13 22  9  7 46 21 12 54 15 19 42 25 20
 29 18 14 24 37 63 76]

Value counts:
number_emergency
0     71667
1      6436
2      1695
3       604
4       320
5       170
6        71
7        62
8        43
10       32
9        22
11       20
13       11
12       10
22        6
16        5
18        5
19        4
20        4
15        3
14        3
21        2
25        2
46        1
54        1
42        1
29        1
24        1
37        1
63        1
76        1
Name: count, dtype: int64

========================================
FEATURE NAME: number_inpatient

Uniqe values:
[ 0  1  2  8  3  6  4  7  5 10  9 12 13 11 15 19 16 14 21]

Value counts:
number_inpatient
0     53354
1     15868
2      6212
3      2796
4      1328
5       672
6       387
7       214
8       116
9        88
10       54
11       42
12       31
13       15
14       10
15        9
16        6
19        2
21        1
Name: count, dtype: int64

========================================
FEATURE NAME: diag_1

Uniqe values:
<ArrowStringArray>
[   '584',    '780',    '599',    '428',    '577',    '179',    '903',
    '458',  '250.8', '250.13',
 ...
    '373',    '632',    '389',    '700',     '10',    '114',    '980',
    '895',    '372',    '500']
Length: 687, dtype: str

Value counts:
diag_1
428    5537
414    5237
786    3072
486    2931
410    2901
       ...
114       1
980       1
895       1
372       1
500       1
Name: count, Length: 687, dtype: int64

========================================
FEATURE NAME: diag_2

Uniqe values:
<ArrowStringArray>
[ '276',  '438',  '820',  '348',  '427',  '250',  '599',  '414',  '881',
  '428',
 ...
  '506',  'V03',  '232',  '350',  '180',  '927',  '752',  '374', 'E915',
  '853']
Length: 720, dtype: str

Value counts:
diag_2
276     5463
428     5349
250     4819
427     3987
401     2882
        ...
927        1
752        1
374        1
E915       1
853        1
Name: count, Length: 720, dtype: int64

========================================
FEATURE NAME: diag_3

Uniqe values:
<ArrowStringArray>
[ '403',  '438', 'E888',  '250',  '511',  'V15',  '285',  '412',  '919',
  '428',
 ...
   '47',  '837',  '884',  '987',  '684', 'E900',  '702',  '146',  '890',
  '353']
Length: 758, dtype: str

Value counts:
diag_3
250     9201
401     6533
276     4247
428     3744
427     3184
        ...
E900       1
702        1
146        1
890        1
353        1
Name: count, Length: 758, dtype: int64

========================================
FEATURE NAME: number_diagnoses

Uniqe values:
[ 9  6  4  8  7  3  5  2  1 16 14 10 12 13 11 15]

Value counts:
number_diagnoses
9     39950
5      9131
8      8433
7      8215
6      7818
4      4318
3      2213
2       835
1       199
16       35
13       15
10       14
11       10
14        7
15        7
12        5
Name: count, dtype: int64

========================================
FEATURE NAME: max_glu_serum

Uniqe values:
<ArrowStringArray>
[nan, 'Norm', '>300', '>200']
Length: 4, dtype: str

Value counts:
max_glu_serum
Norm    1799
>200    1241
>300    1066
Name: count, dtype: int64

========================================
FEATURE NAME: a1cresult

Uniqe values:
<ArrowStringArray>
[nan, '>8', 'Norm', '>7']
Length: 4, dtype: str

Value counts:
a1cresult
>8      7508
Norm    3914
>7      3155
Name: count, dtype: int64

========================================
FEATURE NAME: metformin

Uniqe values:
<ArrowStringArray>
['No', 'Steady', 'Up', 'Down']
Length: 4, dtype: str

Value counts:
metformin
No        61217
Steady    18346
Up         1067
Down        575
Name: count, dtype: int64

========================================
FEATURE NAME: repaglinide

Uniqe values:
<ArrowStringArray>
['No', 'Steady', 'Up', 'Down']
Length: 4, dtype: str

Value counts:
repaglinide
No        79666
Steady     1384
Up          110
Down         45
Name: count, dtype: int64

========================================
FEATURE NAME: nateglinide

Uniqe values:
<ArrowStringArray>
['No', 'Steady', 'Up', 'Down']
Length: 4, dtype: str

Value counts:
nateglinide
No        80502
Steady      668
Up           24
Down         11
Name: count, dtype: int64

========================================
FEATURE NAME: chlorpropamide

Uniqe values:
<ArrowStringArray>
['No', 'Steady', 'Down', 'Up']
Length: 4, dtype: str

Value counts:
chlorpropamide
No        81119
Steady       79
Up            6
Down          1
Name: count, dtype: int64

========================================
FEATURE NAME: glimepiride

Uniqe values:
<ArrowStringArray>
['No', 'Steady', 'Down', 'Up']
Length: 4, dtype: str

Value counts:
glimepiride
No        76014
Steady     4670
Up          327
Down        194
Name: count, dtype: int64

========================================
FEATURE NAME: acetohexamide

Uniqe values:
<ArrowStringArray>
['No', 'Steady']
Length: 2, dtype: str

Value counts:
acetohexamide
No        81204
Steady        1
Name: count, dtype: int64

========================================
FEATURE NAME: glipizide

Uniqe values:
<ArrowStringArray>
['No', 'Steady', 'Up', 'Down']
Length: 4, dtype: str

Value counts:
glipizide
No        68519
Steady    11356
Up          770
Down        560
Name: count, dtype: int64

========================================
FEATURE NAME: glyburide

Uniqe values:
<ArrowStringArray>
['No', 'Steady', 'Down', 'Up']
Length: 4, dtype: str

Value counts:
glyburide
No        70555
Steady     9274
Up          812
Down        564
Name: count, dtype: int64

========================================
FEATURE NAME: tolbutamide

Uniqe values:
<ArrowStringArray>
['No', 'Steady']
Length: 2, dtype: str

Value counts:
tolbutamide
No        81182
Steady       23
Name: count, dtype: int64

========================================
FEATURE NAME: pioglitazone

Uniqe values:
<ArrowStringArray>
['No', 'Steady', 'Up', 'Down']
Length: 4, dtype: str

Value counts:
pioglitazone
No        73877
Steady     6976
Up          234
Down        118
Name: count, dtype: int64

========================================
FEATURE NAME: rosiglitazone

Uniqe values:
<ArrowStringArray>
['No', 'Steady', 'Up', 'Down']
Length: 4, dtype: str

Value counts:
rosiglitazone
No        74840
Steady     6100
Up          178
Down         87
Name: count, dtype: int64

========================================
FEATURE NAME: acarbose

Uniqe values:
<ArrowStringArray>
['No', 'Steady', 'Down', 'Up']
Length: 4, dtype: str

Value counts:
acarbose
No        80897
Steady      295
Up           10
Down          3
Name: count, dtype: int64

========================================
FEATURE NAME: miglitol

Uniqe values:
<ArrowStringArray>
['No', 'Steady', 'Down', 'Up']
Length: 4, dtype: str

Value counts:
miglitol
No        81167
Steady       31
Down          5
Up            2
Name: count, dtype: int64

========================================
FEATURE NAME: troglitazone

Uniqe values:
<ArrowStringArray>
['No', 'Steady']
Length: 2, dtype: str

Value counts:
troglitazone
No        81202
Steady        3
Name: count, dtype: int64

========================================
FEATURE NAME: tolazamide

Uniqe values:
<ArrowStringArray>
['No', 'Steady', 'Up']
Length: 3, dtype: str

Value counts:
tolazamide
No        81166
Steady       38
Up            1
Name: count, dtype: int64

========================================
FEATURE NAME: examide

Uniqe values:
<ArrowStringArray>
['No']
Length: 1, dtype: str

Value counts:
examide
No    81205
Name: count, dtype: int64

========================================
FEATURE NAME: citoglipton

Uniqe values:
<ArrowStringArray>
['No']
Length: 1, dtype: str

Value counts:
citoglipton
No    81205
Name: count, dtype: int64

========================================
FEATURE NAME: insulin

Uniqe values:
<ArrowStringArray>
['Steady', 'No', 'Up', 'Down']
Length: 4, dtype: str

Value counts:
insulin
Steady    30849
No        26822
Down      12218
Up        11316
Name: count, dtype: int64

========================================
FEATURE NAME: glyburide_metformin

Uniqe values:
<ArrowStringArray>
['No', 'Steady', 'Down', 'Up']
Length: 4, dtype: str

Value counts:
glyburide_metformin
No        80499
Steady      692
Up            8
Down          6
Name: count, dtype: int64

========================================
FEATURE NAME: glipizide_metformin

Uniqe values:
<ArrowStringArray>
['No', 'Steady']
Length: 2, dtype: str

Value counts:
glipizide_metformin
No        81192
Steady       13
Name: count, dtype: int64

========================================
FEATURE NAME: glimepiride_pioglitazone

Uniqe values:
<ArrowStringArray>
['No', 'Steady']
Length: 2, dtype: str

Value counts:
glimepiride_pioglitazone
No        81204
Steady        1
Name: count, dtype: int64

========================================
FEATURE NAME: metformin_rosiglitazone

Uniqe values:
<ArrowStringArray>
['No', 'Steady']
Length: 2, dtype: str

Value counts:
metformin_rosiglitazone
No        81203
Steady        2
Name: count, dtype: int64

========================================
FEATURE NAME: metformin_pioglitazone

Uniqe values:
<ArrowStringArray>
['No', 'Steady']
Length: 2, dtype: str

Value counts:
metformin_pioglitazone
No        81204
Steady        1
Name: count, dtype: int64

========================================
FEATURE NAME: change

Uniqe values:
<ArrowStringArray>
['No', 'Ch']
Length: 2, dtype: str

Value counts:
change
Ch    47011
No    34194
Name: count, dtype: int64

========================================
FEATURE NAME: diabetesmed

Uniqe values:
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

Value counts:
diabetesmed
Yes    78363
No      2842
Name: count, dtype: int64


### Remove columns with only one unique value

In [257]:
clean_df = clean_df.loc[:, clean_df.nunique() > 1]
clean_df.shape

(81205, 48)

### Remove columns with missing values ratio

In [258]:
MISSING_THRESHOLD = 0.5

clean_df = clean_df.replace("?", np.nan)
clean_df = clean_df.loc[:, clean_df.isna().mean() < MISSING_THRESHOLD]

clean_df.shape

(81205, 45)

### Remove ID columns

In [259]:
ID_COLUMN = ["encounter_id", "patient_nbr"]

clean_df = clean_df.drop(columns=ID_COLUMN, errors="ignore")
clean_df.shape

(81205, 43)

### Split Train Validation Test

In [260]:
clean_df.groupby("diabetesmed").count()

,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,...,troglitazone,tolazamide,insulin,glyburide_metformin,glipizide_metformin,glimepiride_pioglitazone,metformin_rosiglitazone,metformin_pioglitazone,change,readmitted
diabetesmed,,,,,,,,,,,,,,,,,,,,,
No,2800,2842,2842,2842,2842,2842,2842,1514,1398,2842,...,2842,2842,2842,2842,2842,2842,2842,2842,2842,2842
Yes,76492,78363,78363,78363,78363,78363,78363,48949,40396,78363,...,78363,78363,78363,78363,78363,78363,78363,78363,78363,78363

In [261]:
# Features
X = clean_df.drop(columns=["diabetesmed"])

# Target
y = clean_df["diabetesmed"]

print(f"X shape: {X.shape}")
print(f"y shape: {y.shape}")

X shape: (81205, 42)
y shape: (81205,)

In [262]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=RANDOM_STATE,
    stratify=y,  # good for classification if classes are imbalanced
)

print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_test shape: {y_test.shape}")

X_train shape: (64964, 42)
y_train shape: (64964,)
X_test shape: (16241, 42)
y_test shape: (16241,)

In [263]:
y_train.value_counts(normalize=True)

diabetesmed
Yes    0.964996
No     0.035004
Name: proportion, dtype: float64

### Categorize data

In [264]:
for column in X_train.columns:
    print()
    print("==" * 20)
    print("FEATURE NAME:", column)
    print()
    print("Uniqe values:")
    print(X_train[column].unique())
    print()
    print("Value counts:")
    print(X_train[column].value_counts())

========================================
FEATURE NAME: race

Uniqe values:
<ArrowStringArray>
['Caucasian', 'AfricanAmerican', 'Hispanic', 'Asian', 'Other', nan]
Length: 6, dtype: str

Value counts:
race
Caucasian          48499
AfricanAmerican    12267
Hispanic            1281
Other                989
Asian                392
Name: count, dtype: int64

========================================
FEATURE NAME: gender

Uniqe values:
<ArrowStringArray>
['Male', 'Female', 'Unknown/Invalid']
Length: 3, dtype: str

Value counts:
gender
Female             34746
Male               30217
Unknown/Invalid        1
Name: count, dtype: int64

========================================
FEATURE NAME: age

Uniqe values:
<ArrowStringArray>
[ '[50-60)',  '[70-80)',  '[80-90)',  '[60-70)',  '[40-50)',  '[20-30)',
 '[90-100)',  '[30-40)',  '[10-20)',   '[0-10)']
Length: 10, dtype: str

Value counts:
age
[70-80)     16764
[60-70)     14552
[50-60)     11088
[80-90)     10727
[40-50)      6155
[30-40)      2374
[90-100)     1652
[20-30)      1060
[10-20)       482
[0-10)        110
Name: count, dtype: int64

========================================
FEATURE NAME: admission_type_id

Uniqe values:
[1 2 3 6 5 8 7 4]

Value counts:
admission_type_id
1    34319
3    12086
2    11910
5     3235
6     3171
8      224
7       15
4        4
Name: count, dtype: int64

========================================
FEATURE NAME: discharge_disposition_id

Uniqe values:
[ 1  6  3  2 18 28 25  5  7 11 23 22  4 13 14 15 16 24  8  9 10 19 17 20
 27]

Value counts:
discharge_disposition_id
1     38486
3      9105
6      8562
18     1977
22     1368
2      1295
11      927
5       732
25      617
4       483
7       371
23      294
13      243
14      220
28       91
8        68
15       49
24       32
9        14
16       10
17        9
10        4
19        3
20        2
27        2
Name: count, dtype: int64

========================================
FEATURE NAME: admission_source_id

Uniqe values:
[ 7  4  1 17  2  6  9  5 10  3 22 20  8 25 13 14 11]

Value counts:
admission_source_id
7     36678
1     18854
17     4367
4      2052
6      1489
2       703
5       465
3       113
20      111
9        94
8        14
22       11
10        8
25        2
13        1
14        1
11        1
Name: count, dtype: int64

========================================
FEATURE NAME: time_in_hospital

Uniqe values:
[ 1  2  5  8  3  7 12  4  6 13 10  9 11 14]

Value counts:
time_in_hospital
3     11380
2     10830
4      9016
1      8289
5      6502
6      4928
7      3820
8      2887
9      2012
10     1537
11     1256
12      976
13      819
14      712
Name: count, dtype: int64

========================================
FEATURE NAME: payer_code

Uniqe values:
<ArrowStringArray>
['BC', 'MC', 'CM', 'CP',  nan, 'HM', 'MD', 'OG', 'SP', 'SI', 'DM', 'UN', 'OT',
 'WC', 'CH', 'PO', 'MP', 'FR']
Length: 18, dtype: str

Value counts:
payer_code
MC    21324
HM     3801
SP     3398
BC     2978
MD     2445
CP     1648
UN     1631
CM     1303
OG      713
DM      388
PO      383
CH       99
WC       90
OT       61
MP       55
SI       30
FR        1
Name: count, dtype: int64

========================================
FEATURE NAME: medical_specialty

Uniqe values:
<ArrowStringArray>
[                                   nan,
                     'Emergency/Trauma',
    'PhysicalMedicineandRehabilitation',
                     'InternalMedicine',
                          'Pulmonology',
               'Family/GeneralPractice',
                           'Cardiology',
                             'Podiatry',
                     'Gastroenterology',
                      'Surgery-General',
                       'Otolaryngology',
                           'Pediatrics',
                     'Surgery-Vascular',
      'Surgery-Cardiovascular/Thoracic',
                           'Gynecology',
                             'Oncology',
                           'Nephrology',
                           'Psychiatry',
      'Pediatrics-AllergyandImmunology',
             'Pediatrics-Endocrinology',
                              'Urology',
              'ObstetricsandGynecology',
           'Orthopedics-Reconstructive',
                          'Radiologist',
               'Surgery-Cardiovascular',
                          'Orthopedics',
                        'Surgery-Neuro',
                     'Surgery-Thoracic',
                    'Surgery-Pediatric',
                  'Hematology/Oncology',
               'Pediatrics-Pulmonology',
                        'Endocrinology',
                   'InfectiousDiseases',
                              'DCPTEAM',
                            'Neurology',
                           'Hematology',
                              'Surgeon',
                               'Speech',
                           'Psychology',
                    'SurgicalSpecialty',
             'Anesthesiology-Pediatric',
          'Psychiatry-Child/Adolescent',
 'Obsterics&Gynecology-GynecologicOnco',
                            'Radiology',
                        'Ophthalmology',
                            'Osteopath',
                 'Pediatrics-Neurology',
                       'Anesthesiology',
              'Pediatrics-CriticalCare',
                            'Pathology',
                           'Obstetrics',
                          'Hospitalist',
                 'Surgery-Colon&Rectal',
                      'Surgery-Plastic',
                     'OutreachServices',
                 'Cardiology-Pediatric',
                    'PhysicianNotFound',
             'Endocrinology-Metabolism',
                 'AllergyandImmunology',
                         'Rheumatology',
         'Pediatrics-EmergencyMedicine',
                'Surgery-Maxillofacial',
                            'Dentistry',
                         'Perinatology',
                           'Proctology',
        'Pediatrics-InfectiousDiseases',
                       'SportsMedicine',
                             'Resident',
                          'Dermatology',
       'Pediatrics-Hematology-Oncology',
                      'Neurophysiology',
     'Surgery-PlasticwithinHeadandNeck']
Length: 72, dtype: str

Value counts:
medical_specialty
InternalMedicine                    9367
Emergency/Trauma                    5107
Family/GeneralPractice              4891
Cardiology                          3315
Surgery-General                     1882
                                    ...
Pediatrics-InfectiousDiseases          1
SportsMedicine                         1
Dermatology                            1
Neurophysiology                        1
Surgery-PlasticwithinHeadandNeck       1
Name: count, Length: 71, dtype: int64

========================================
FEATURE NAME: num_lab_procedures

Uniqe values:
[ 37  46   1  58  62  26  39  61  19  50  38   3  31  36  40  45  80  74
  41  20  27  29  66  44  48  43  60  49 102  59  47  73  22   9  55  25
  35  53  52  18  34  71  10  42  56  64 101  30  51  76  24  67  54  65
  32  78  17  83  21  12  72  77  28  11  33  88  79  82   2  16  63   8
  14  81  69  57  23  68   4   6  87  15  70   5  85  75  97  13   7  95
  90  99  86  91 103  84  89  98  94  93  96  92 106 113 105 120 111 100
 129 132 118 104 108 109 114 121]

Value counts:
num_lab_procedures
1      2116
43     1787
44     1575
45     1523
46     1373
       ...
132       1
118       1
104       1
114       1
121       1
Name: count, Length: 116, dtype: int64

========================================
FEATURE NAME: num_procedures

Uniqe values:
[0 1 3 6 4 5 2]

Value counts:
num_procedures
0    30224
1    13080
2     7889
3     5900
6     3203
4     2699
5     1969
Name: count, dtype: int64

========================================
FEATURE NAME: num_medications

Uniqe values:
[12 25 16  9 22 21 20  7 26 15 10 19 48 29  5  8 13  6 31 34 24 30 27  4
 11 18 14 23 17  3 38 33 36 42 28 35 43 40 45  2 55 60 47 65 52 39  1 32
 54 50 44 72 37 46 57 56 51 53 41 59 69 63 49 74 62 58 61 64 70 67 66 68
 75 79]

Value counts:
num_medications
13    3849
15    3771
12    3750
14    3694
11    3631
      ...
66       3
70       2
75       2
74       1
79       1
Name: count, Length: 74, dtype: int64

========================================
FEATURE NAME: number_outpatient

Uniqe values:
[ 2  0  1  3  4 14  5 12  6  7 10 13 11  8 20  9 15 24 25 26 19 22 33 16
 23 17 40 27 35 18 37 21 36 29 38 34]

Value counts:
number_outpatient
0     54101
1      5515
2      2353
3      1354
4       713
5       334
6       188
7        97
8        64
9        49
10       42
11       31
13       23
12       22
14       21
15       14
16        5
20        4
22        4
17        4
24        2
25        2
19        2
33        2
23        2
27        2
35        2
18        2
36        2
29        2
26        1
40        1
37        1
21        1
38        1
34        1
Name: count, dtype: int64

========================================
FEATURE NAME: number_emergency

Uniqe values:
[ 0  2  5  1  3  4  8  7  9 11 16 10 20 14 15  6 12 13 22 76 18 29 24 46
 25 19 37 21]

Value counts:
number_emergency
0     57344
1      5138
2      1357
3       476
4       251
5       139
6        60
7        50
8        35
10       24
9        19
11       17
12       10
13        8
22        6
16        4
20        4
18        4
19        4
14        3
15        2
25        2
21        2
76        1
29        1
24        1
46        1
37        1
Name: count, dtype: int64

========================================
FEATURE NAME: number_inpatient

Uniqe values:
[ 0  1 11  2  3 15  4  6  5 13  7  9  8 10 12 16 14 19 21]

Value counts:
number_inpatient
0     42708
1     12696
2      4964
3      2216
4      1040
5       536
6       313
7       181
8        92
9        69
10       46
11       37
12       27
13       13
14        9
15        8
16        6
19        2
21        1
Name: count, dtype: int64

========================================
FEATURE NAME: diag_1

Uniqe values:
<ArrowStringArray>
[  '511',   '410',   '540',   '434',   '428',   'V57',   '493',   '293',
 '250.7',   '427',
 ...
    '52',   '217',   '216',   '363',   '142',   '955',   '871',   '114',
   '147',    '84']
Length: 663, dtype: str

Value counts:
diag_1
428    4406
414    4244
786    2471
486    2372
410    2330
       ...
955       1
871       1
114       1
147       1
84        1
Name: count, Length: 662, dtype: int64

========================================
FEATURE NAME: diag_2

Uniqe values:
<ArrowStringArray>
['428', '585', '552', '250', '599', '438', '799', '401', '518', '440',
 ...
 '195', '755', '212', '306', '186', '501', '374', '910', '912', '980']
Length: 694, dtype: str

Value counts:
diag_2
276    4341
428    4293
250    3899
427    3179
401    2343
       ...
501       1
374       1
910       1
912       1
980       1
Name: count, Length: 693, dtype: int64

========================================
FEATURE NAME: diag_3

Uniqe values:
<ArrowStringArray>
[   '696', '250.42',    '278',    '244',     '41',    '414',    '438',
    '493',    '276',    '401',
 ...
   'E938',    '864',    'V70',    '448',    '265',    '483',    'V07',
     '17',   'E865',   'E949']
Length: 737, dtype: str

Value counts:
diag_3
250     7376
401     5240
276     3364
428     2982
427     2606
        ...
483        1
V07        1
17         1
E865       1
E949       1
Name: count, Length: 736, dtype: int64

========================================
FEATURE NAME: number_diagnoses

Uniqe values:
[ 9  6  7  8  4  5  2  3  1 10 16 11 13 12 14 15]

Value counts:
number_diagnoses
9     31841
5      7353
8      6782
7      6603
6      6288
4      3420
3      1781
2       655
1       165
16       25
13       15
10       13
11        7
15        7
14        5
12        4
Name: count, dtype: int64

========================================
FEATURE NAME: metformin

Uniqe values:
<ArrowStringArray>
['Steady', 'No', 'Down', 'Up']
Length: 4, dtype: str

Value counts:
metformin
No        48961
Steady    14701
Up          838
Down        464
Name: count, dtype: int64

========================================
FEATURE NAME: repaglinide

Uniqe values:
<ArrowStringArray>
['No', 'Steady', 'Down', 'Up']
Length: 4, dtype: str

Value counts:
repaglinide
No        63747
Steady     1094
Up           87
Down         36
Name: count, dtype: int64

========================================
FEATURE NAME: nateglinide

Uniqe values:
<ArrowStringArray>
['No', 'Steady', 'Down', 'Up']
Length: 4, dtype: str

Value counts:
nateglinide
No        64413
Steady      520
Up           21
Down         10
Name: count, dtype: int64

========================================
FEATURE NAME: chlorpropamide

Uniqe values:
<ArrowStringArray>
['No', 'Steady', 'Down', 'Up']
Length: 4, dtype: str

Value counts:
chlorpropamide
No        64888
Steady       69
Up            6
Down          1
Name: count, dtype: int64

========================================
FEATURE NAME: glimepiride

Uniqe values:
<ArrowStringArray>
['No', 'Steady', 'Up', 'Down']
Length: 4, dtype: str

Value counts:
glimepiride
No        60827
Steady     3722
Up          256
Down        159
Name: count, dtype: int64

========================================
FEATURE NAME: acetohexamide

Uniqe values:
<ArrowStringArray>
['No', 'Steady']
Length: 2, dtype: str

Value counts:
acetohexamide
No        64963
Steady        1
Name: count, dtype: int64

========================================
FEATURE NAME: glipizide

Uniqe values:
<ArrowStringArray>
['No', 'Steady', 'Up', 'Down']
Length: 4, dtype: str

Value counts:
glipizide
No        54830
Steady     9094
Up          605
Down        435
Name: count, dtype: int64

========================================
FEATURE NAME: glyburide

Uniqe values:
<ArrowStringArray>
['No', 'Steady', 'Up', 'Down']
Length: 4, dtype: str

Value counts:
glyburide
No        56424
Steady     7418
Up          660
Down        462
Name: count, dtype: int64

========================================
FEATURE NAME: tolbutamide

Uniqe values:
<ArrowStringArray>
['No', 'Steady']
Length: 2, dtype: str

Value counts:
tolbutamide
No        64945
Steady       19
Name: count, dtype: int64

========================================
FEATURE NAME: pioglitazone

Uniqe values:
<ArrowStringArray>
['No', 'Steady', 'Up', 'Down']
Length: 4, dtype: str

Value counts:
pioglitazone
No        59130
Steady     5548
Up          185
Down        101
Name: count, dtype: int64

========================================
FEATURE NAME: rosiglitazone

Uniqe values:
<ArrowStringArray>
['No', 'Steady', 'Up', 'Down']
Length: 4, dtype: str

Value counts:
rosiglitazone
No        59910
Steady     4845
Up          140
Down         69
Name: count, dtype: int64

========================================
FEATURE NAME: acarbose

Uniqe values:
<ArrowStringArray>
['No', 'Steady', 'Up', 'Down']
Length: 4, dtype: str

Value counts:
acarbose
No        64724
Steady      229
Up            9
Down          2
Name: count, dtype: int64

========================================
FEATURE NAME: miglitol

Uniqe values:
<ArrowStringArray>
['No', 'Steady', 'Up', 'Down']
Length: 4, dtype: str

Value counts:
miglitol
No        64932
Steady       26
Down          4
Up            2
Name: count, dtype: int64

========================================
FEATURE NAME: troglitazone

Uniqe values:
<ArrowStringArray>
['No', 'Steady']
Length: 2, dtype: str

Value counts:
troglitazone
No        64962
Steady        2
Name: count, dtype: int64

========================================
FEATURE NAME: tolazamide

Uniqe values:
<ArrowStringArray>
['No', 'Up', 'Steady']
Length: 3, dtype: str

Value counts:
tolazamide
No        64930
Steady       33
Up            1
Name: count, dtype: int64

========================================
FEATURE NAME: insulin

Uniqe values:
<ArrowStringArray>
['No', 'Steady', 'Down', 'Up']
Length: 4, dtype: str

Value counts:
insulin
Steady    24678
No        21525
Down       9768
Up         8993
Name: count, dtype: int64

========================================
FEATURE NAME: glyburide_metformin

Uniqe values:
<ArrowStringArray>
['No', 'Down', 'Steady', 'Up']
Length: 4, dtype: str

Value counts:
glyburide_metformin
No        64395
Steady      556
Up            8
Down          5
Name: count, dtype: int64

========================================
FEATURE NAME: glipizide_metformin

Uniqe values:
<ArrowStringArray>
['No', 'Steady']
Length: 2, dtype: str

Value counts:
glipizide_metformin
No        64952
Steady       12
Name: count, dtype: int64

========================================
FEATURE NAME: glimepiride_pioglitazone

Uniqe values:
<ArrowStringArray>
['No', 'Steady']
Length: 2, dtype: str

Value counts:
glimepiride_pioglitazone
No        64963
Steady        1
Name: count, dtype: int64

========================================
FEATURE NAME: metformin_rosiglitazone

Uniqe values:
<ArrowStringArray>
['No', 'Steady']
Length: 2, dtype: str

Value counts:
metformin_rosiglitazone
No        64963
Steady        1
Name: count, dtype: int64

========================================
FEATURE NAME: metformin_pioglitazone

Uniqe values:
<ArrowStringArray>
['No', 'Steady']
Length: 2, dtype: str

Value counts:
metformin_pioglitazone
No        64963
Steady        1
Name: count, dtype: int64

========================================
FEATURE NAME: change

Uniqe values:
<ArrowStringArray>
['No', 'Ch']
Length: 2, dtype: str

Value counts:
change
Ch    37509
No    27455
Name: count, dtype: int64

========================================
FEATURE NAME: readmitted

Uniqe values:
<ArrowStringArray>
['NO', '>30', '<30']
Length: 3, dtype: str

Value counts:
readmitted
NO     34174
>30    23274
<30     7516
Name: count, dtype: int64

In [265]:
# ORDER_CATEGORIES = [
#     # age
#     [
#         "[0-10)",
#         "[10-20)",
#         "[20-30)",
#         "[30-40)",
#         "[40-50)",
#         "[50-60)",
#         "[60-70)",
#         "[70-80)",
#         "[80-90)",
#         "[90-100)",
#     ],
#     # medication columns
#     ["No", "Steady", "Up", "Down"],  # metformin
#     ["No", "Steady", "Up", "Down"],  # repaglinide
#     ["No", "Steady", "Up", "Down"],  # nateglinide
#     ["No", "Steady", "Up", "Down"],  # chlorpropamide
#     ["No", "Steady", "Up", "Down"],  # glimepiride
#     ["No", "Steady", "Up", "Down"],  # glipizide
#     ["No", "Steady", "Up", "Down"],  # glyburide
#     ["No", "Steady", "Up", "Down"],  # pioglitazone
#     ["No", "Steady", "Up", "Down"],  # rosiglitazone
#     ["No", "Steady", "Up", "Down"],  # acarbose
#     ["No", "Steady", "Up", "Down"],  # miglitol
#     # this one does not contain Down
#     ["No", "Steady", "Up"],  # tolazamide
#     ["No", "Steady", "Up", "Down"],  # insulin
#     ["No", "Steady", "Up", "Down"],  # glyburide_metformin
#     # target-style ordinal
#     ["NO", ">30", "<30"],  # readmitted
# ]

In [266]:
ORDER_CATEGORIES = [
    # age
    [
        "[0-10)",
        "[10-20)",
        "[20-30)",
        "[30-40)",
        "[40-50)",
        "[50-60)",
        "[60-70)",
        "[70-80)",
        "[80-90)",
        "[90-100)",
    ],
    # readmitted
    ["NO", ">30", "<30"],
    # change
    ["No", "Ch"],
]

In [267]:
# NUMERIC_COLUMNS = [
#     "time_in_hospital",
#     "num_lab_procedures",
#     "num_procedures",
#     "num_medications",
#     "number_outpatient",
#     "number_emergency",
#     "number_inpatient",
#     "number_diagnoses",
# ]

# NON_ORDER_CATEGORY_COLUMNS = [
#     "race",
#     "gender",
#     "admission_type_id",
#     "discharge_disposition_id",
#     "admission_source_id",
#     "payer_code",
#     "medical_specialty",
#     "diag_1",
#     "diag_2",
#     "diag_3",
#     "acetohexamide",
#     "tolbutamide",
#     "troglitazone",
#     "glipizide_metformin",
#     "glimepiride_pioglitazone",
#     "metformin_rosiglitazone",
#     "metformin_pioglitazone",
#     "change",
# ]

# ORDER_CATEGORY_COLUMNS = [
#     "age",
#     "metformin",
#     "repaglinide",
#     "nateglinide",
#     "chlorpropamide",
#     "glimepiride",
#     "glipizide",
#     "glyburide",
#     "pioglitazone",
#     "rosiglitazone",
#     "acarbose",
#     "miglitol",
#     "tolazamide",
#     "insulin",
#     "glyburide_metformin",
#     "readmitted",
# ]

# print(f"NUMERIC_COLUMNS: {len(NUMERIC_COLUMNS)}")
# print(f"NON_ORDER_CATEGORY_COLUMNS: {len(NON_ORDER_CATEGORY_COLUMNS)}")
# print(f"ORDER_CATEGORY_COLUMNS: {len(ORDER_CATEGORY_COLUMNS)}")
# print(f"X_train columns: {len(X_train.columns)}")
# print(
#     len(NUMERIC_COLUMNS) + len(NON_ORDER_CATEGORY_COLUMNS) + len(ORDER_CATEGORY_COLUMNS)
#     == len(X_train.columns)
# )

# all_defined_columns = (
#     NUMERIC_COLUMNS + NON_ORDER_CATEGORY_COLUMNS + ORDER_CATEGORY_COLUMNS
# )

# missing_columns = [col for col in X_train.columns if col not in all_defined_columns]

# print("Columns in X_train but not in the 3 sets:")
# print(missing_columns)
# print("Count:", len(missing_columns))

In [268]:
NUMERIC_COLUMNS = [
    "time_in_hospital",
    "num_lab_procedures",
    "num_procedures",
    "num_medications",
    "number_outpatient",
    "number_emergency",
    "number_inpatient",
    "number_diagnoses",
]

NON_ORDER_CATEGORY_COLUMNS = [
    "race",
    "gender",
    "admission_type_id",
    "discharge_disposition_id",
    "admission_source_id",
    "payer_code",
    "medical_specialty",
    "diag_1",
    "diag_2",
    "diag_3",
]

ORDER_CATEGORY_COLUMNS = [
    "age",
    "readmitted",
    "change",
]

print(f"NUMERIC_COLUMNS: {len(NUMERIC_COLUMNS)}")
print(f"NON_ORDER_CATEGORY_COLUMNS: {len(NON_ORDER_CATEGORY_COLUMNS)}")
print(f"ORDER_CATEGORY_COLUMNS: {len(ORDER_CATEGORY_COLUMNS)}")
print(f"X_train columns: {len(X_train.columns)}")
print(
    len(NUMERIC_COLUMNS) + len(NON_ORDER_CATEGORY_COLUMNS) + len(ORDER_CATEGORY_COLUMNS)
    == len(X_train.columns)
)

all_defined_columns = (
    NUMERIC_COLUMNS + NON_ORDER_CATEGORY_COLUMNS + ORDER_CATEGORY_COLUMNS
)

missing_columns = [col for col in X_train.columns if col not in all_defined_columns]

print("Columns in X_train but not in the 3 sets:")
print(missing_columns)
print("Count:", len(missing_columns))

NUMERIC_COLUMNS: 8
NON_ORDER_CATEGORY_COLUMNS: 10
ORDER_CATEGORY_COLUMNS: 3
X_train columns: 42
False
Columns in X_train but not in the 3 sets:
['metformin', 'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide', 'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone', 'tolazamide', 'insulin', 'glyburide_metformin', 'glipizide_metformin', 'glimepiride_pioglitazone', 'metformin_rosiglitazone', 'metformin_pioglitazone']
Count: 21

In [269]:
X_train = X_train[all_defined_columns]
X_train.shape

(64964, 21)

In [270]:
y_train.shape

(64964,)

### Train Model - Basic LogisticRegression

In [271]:
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score

# encode target
y_train = y_train.map({"Yes": 1, "No": 0})
y_test = y_test.map({"Yes": 1, "No": 0})

# preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), NUMERIC_COLUMNS),
        ("cat", OneHotEncoder(handle_unknown="ignore"), NON_ORDER_CATEGORY_COLUMNS),
        ("ord", OrdinalEncoder(categories=ORDER_CATEGORIES), ORDER_CATEGORY_COLUMNS),
    ]
)

# pipeline
pipeline = Pipeline(
    [
        ("preprocessor", preprocessor),
        ("model", LogisticRegression(max_iter=3000, class_weight="balanced")),
    ]
)

# grid parameters
param_grid = {
    "model__C": [0.01, 0.1, 1, 10, 50],
    "model__solver": ["lbfgs", "liblinear"],
    "model__penalty": ["l2"]
}

# grid search
grid = GridSearchCV(
    pipeline,
    param_grid,
    cv=5,
    scoring="roc_auc",
    n_jobs=-1,
    verbose=1
)

# train
grid.fit(X_train, y_train)

print("Best parameters:", grid.best_params_)
print("Best CV ROC AUC:", grid.best_score_)

# best model
best_model = grid.best_estimator_

# predict
y_pred = best_model.predict(X_test)
y_prob = best_model.predict_proba(X_test)[:, 1]

# evaluation
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nROC AUC:", roc_auc_score(y_test, y_prob))

Fitting 5 folds for each of 10 candidates, totalling 50 fits

d:\GIT\diabetes_classification\mt_env\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(

Best parameters: {'model__C': 0.01, 'model__penalty': 'l2', 'model__solver': 'lbfgs'}
Best CV ROC AUC: 0.8410487502607455
Confusion Matrix:
 [[ 560    8]
 [5880 9793]]

Classification Report:
               precision    recall  f1-score   support

           0       0.09      0.99      0.16       568
           1       1.00      0.62      0.77     15673

    accuracy                           0.64     16241
   macro avg       0.54      0.81      0.46     16241
weighted avg       0.97      0.64      0.75     16241


ROC AUC: 0.8415754688919583